# Site settings
title: Semana-I static website
email: t.nadalie33@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This static web-site was made by thomas Nadalié during the Semana-I GitHub activity.
baseurl: "/github_semanaI" # the subpath of your site, e.g. /blog/
url: "http://jeanrachid.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jeanrachid

# Build settings
markdown: kramdown
